Select question_id, team_number, answer from team102_2014.answers
USE team102_2014;

CREATE TABLE `answers` (
  `question_id` int(11) NOT NULL,
  `team_number` int(11) NOT NULL,
  `answer` varchar(2046) DEFAULT NULL,
  PRIMARY KEY (`question_id`,`team_number`),
  KEY `answer_team_fk` (`team_number`),
  CONSTRAINT `answer_team_fk` FOREIGN KEY (`team_number`) REFERENCES `teams` (`number`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,11,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,41,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,56,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,75,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,102,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,193,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,219,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,222,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,555,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,613,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,1228,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,1279,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,1302,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,1370,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,1403,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,1676,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,1811,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,1923,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,2070,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,2458,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,2554,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,2559,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,2577,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,2600,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,3142,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,3314,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,3340,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,3515,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,3637,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,4281,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,4285,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,4361,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,4650,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (0,4653,'Save');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,11,'OTHER');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,41,'TANK');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,56,'TANK');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,75,'TANK');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,102,'MECANUM');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,193,'TANK');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,219,'TANK');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,222,'TANK');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,555,'MECANUM');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,613,'TANK');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,1228,'TANK');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,1279,'TANK');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,1302,'OTHER');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,1370,'MECANUM');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,1403,'OTHER');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,1676,'TANK');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,1811,'MECANUM');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,1923,'TANK');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,2070,'TANK');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,2458,'TANK');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,2554,'TANK');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,2559,'TANK');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,2577,'MECANUM');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,2600,'MECANUM');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,3142,'MECANUM');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,3314,'MECANUM');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,3340,'MECANUM');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,3515,'TANK');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,3637,'MECANUM');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,4281,'TANK');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,4285,'TANK');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,4361,'TANK');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,4650,'TANK');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (2,4653,'MECANUM');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,11,'8');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,41,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,56,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,75,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,102,'4');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,193,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,219,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,222,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,555,'4');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,613,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,1228,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,1279,'8');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,1302,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,1370,'4');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,1403,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,1676,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,1811,'4');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,1923,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,2070,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,2458,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,2554,'4');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,2559,'3');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,2577,'4');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,2600,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,3142,'4');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,3314,'4');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,3340,'4');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,3515,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,3637,'4');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,4281,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,4285,'8');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,4361,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,4650,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (3,4653,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,11,'BELT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,41,'CHAIN');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,56,'BELT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,75,'BELT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,102,'DIRECT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,193,'BELT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,219,'BELT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,222,'CHAIN');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,555,'DIRECT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,613,'BELT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,1228,'BELT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,1279,'CHAIN');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,1302,'BELT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,1370,'DIRECT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,1403,'BELT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,1676,'CHAIN');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,1811,'BELT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,1923,'CHAIN');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,2070,'BELT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,2458,'BELT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,2554,'CHAIN');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,2559,'BELT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,2577,'DIRECT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,2600,'BELT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,3142,'DIRECT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,3314,'DIRECT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,3340,'DIRECT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,3515,'BELT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,3637,'DIRECT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,4281,'BELT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,4285,'CHAIN');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,4361,'BELT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,4650,'BELT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (4,4653,'BELT');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,11,'2');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,41,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,56,'4');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,75,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,102,'4');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,193,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,219,'4');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,222,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,555,'4');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,613,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,1228,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,1279,'8');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,1302,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,1370,'4');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,1403,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,1676,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,1811,'4');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,1923,'2');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,2070,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,2458,'2');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,2554,'4');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,2559,'1');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,2577,'4');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,2600,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,3142,'4');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,3314,'4');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,3340,'4');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,3515,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,3637,'4');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,4281,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,4285,'8');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,4361,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,4650,'2');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (5,4653,'6');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,11,'16');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,41,'16');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,56,'Somewhat fast');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,75,'2');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,102,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,193,'13');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,219,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,222,'18');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,555,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,613,'20');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,1228,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,1279,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,1302,'16');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,1370,'Fast');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,1403,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,1676,'22');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,1811,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,1923,'12');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,2070,'Slow');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,2458,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,2554,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,2559,'15');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,2577,'Very fast');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,2600,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,3142,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,3314,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,3340,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,3515,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,3637,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,4281,'10');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,4285,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,4361,'Above avg');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,4650,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (6,4653,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,11,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,41,'Very high');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,56,'Pretty high');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,75,'9.25');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,102,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,193,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,219,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,222,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,555,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,613,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,1228,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,1279,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,1302,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,1370,'12');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,1403,'A lot');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,1676,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,1811,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,1923,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,2070,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,2458,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,2554,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,2559,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,2577,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,2600,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,3142,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,3314,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,3340,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,3515,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,3637,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,4281,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,4285,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,4361,'Unknown');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,4650,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (7,4653,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,11,'None');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,41,'None');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,56,'The side');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,75,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,102,'Right');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,193,'None');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,219,'None');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,222,'Either side not middle');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,555,'On the line in the ');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,613,'None');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,1228,'The white line');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,1279,'Anywhere');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,1302,'No');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,1370,'None');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,1403,'Center');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,1676,'With cube');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,1811,'18ft from 1 point goal');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,1923,'No');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,2070,'Line');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,2458,'None');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,2554,'No autonomous');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,2559,'On the line');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,2577,'Anywhere');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,2600,'Middle');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,3142,'Left or middle');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,3314,'No');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,3340,'No');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,3515,'Sides');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,3637,'middle');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,4281,'The line');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,4285,'No');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,4361,'In front of goals ');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,4650,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (9,4653,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,11,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,41,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,56,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,75,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,102,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,193,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,219,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,222,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,555,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,613,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,1228,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,1279,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,1302,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,1370,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,1403,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,1676,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,1811,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,1923,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,2070,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,2458,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,2554,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,2559,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,2577,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,2600,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,3142,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,3314,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,3340,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,3515,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,3637,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,4281,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,4285,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,4361,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,4650,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (10,4653,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,11,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,41,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,56,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,75,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,102,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,193,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,219,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,222,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,555,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,613,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,1228,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,1279,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,1302,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,1370,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,1403,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,1676,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,1811,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,1923,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,2070,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,2458,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,2554,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,2559,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,2577,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,2600,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,3142,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,3314,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,3340,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,3515,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,3637,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,4281,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,4285,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,4361,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,4650,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (11,4653,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,11,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,41,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,56,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,75,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,102,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,193,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,219,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,222,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,555,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,613,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,1228,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,1279,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,1302,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,1370,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,1403,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,1676,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,1811,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,1923,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,2070,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,2458,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,2554,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,2559,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,2577,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,2600,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,3142,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,3314,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,3340,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,3515,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,3637,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,4281,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,4285,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,4361,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,4650,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (12,4653,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,11,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,41,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,56,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,75,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,102,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,193,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,219,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,222,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,555,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,613,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,1228,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,1279,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,1302,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,1370,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,1403,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,1676,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,1811,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,1923,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,2070,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,2458,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,2554,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,2559,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,2577,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,2600,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,3142,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,3314,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,3340,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,3515,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,3637,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,4281,'YES');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,4285,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,4361,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,4650,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (13,4653,'NO');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,11,'Shoot ,mobility');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,41,'Drive forward');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,56,'Move up and then score in the high goal');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,75,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,102,'Drive straight and drop in low goal');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,193,'5 different versions');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,219,'Pick up and shoot');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,222,'Drives or shoot');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,555,'Drive forward and shoot');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,613,'Moves forward');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,1228,'Shoot in high goal');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,1279,'Shoot at hot goal then move');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,1302,'Shoots and moves');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,1370,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,1403,'Shoots as often as possible');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,1676,'Drive and shoot, just drive');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,1811,'Lowers arm goes forward shoots ');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,1923,'Detects hot goal and shoots');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,2070,'Just move forward');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,2458,'Goes forward');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,2554,'Doesn''t use it');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,2559,'Move forward and shoot');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,2577,'Take a shot and drive forward');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,2600,'Move forward');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,3142,'Move forward');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,3314,'Moves and shoots');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,3340,'Move forward');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,3515,'Move up');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,3637,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,4281,'Shoot and pickup ');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,4285,'Shoot high move forward');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,4361,'Shoot score them wait');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,4650,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (14,4653,'Score then drive forward');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,11,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,41,'50');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,56,'90%');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,75,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,102,'10');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,193,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,219,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,222,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,555,'90');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,613,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,1228,'90');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,1279,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,1302,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,1370,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,1403,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,1676,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,1811,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,1923,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,2070,'0');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,2458,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,2554,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,2559,'Pretty accurate ');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,2577,'90%');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,2600,'80');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,3142,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,3314,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,3340,'Na');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,3515,'Na');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,3637,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,4281,'75');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,4285,'60');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,4361,'70');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,4650,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (16,4653,'Mostly');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,11,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,41,'Not shooting in low');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,56,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,75,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,102,'90');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,193,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,219,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,222,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,555,'N/A');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,613,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,1228,'75');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,1279,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,1302,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,1370,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,1403,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,1676,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,1811,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,1923,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,2070,'60');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,2458,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,2554,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,2559,'60');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,2577,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,2600,'90');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,3142,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,3314,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,3340,'90');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,3515,'90');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,3637,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,4281,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,4285,'90');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,4361,'80');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,4650,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (17,4653,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,11,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,41,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,56,'95');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,75,'95');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,102,'80');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,193,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,219,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,222,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,555,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,613,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,1228,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,1279,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,1302,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,1370,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,1403,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,1676,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,1811,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,1923,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,2070,'0');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,2458,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,2554,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,2559,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,2577,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,2600,'90');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,3142,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,3314,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,3340,'Na');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,3515,'Na');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,3637,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,4281,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,4285,'99');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,4361,'Not consistent ');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,4650,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (18,4653,'50');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,11,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,41,'0');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,56,'0');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,75,'Maybe');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,102,'60');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,193,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,219,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,222,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,555,'No');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,613,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,1228,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,1279,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,1302,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,1370,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,1403,'90');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,1676,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,1811,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,1923,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,2070,'0');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,2458,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,2554,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,2559,'0');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,2577,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,2600,'Na');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,3142,'60');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,3314,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,3340,'90');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,3515,'70');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,3637,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,4281,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,4285,'Na');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,4361,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,4650,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (19,4653,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,11,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,41,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,56,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,75,'Yes');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,102,'0');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,193,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,219,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,222,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,555,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,613,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,1228,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,1279,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,1302,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,1370,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,1403,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,1676,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,1811,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,1923,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,2070,'0');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,2458,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,2554,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,2559,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,2577,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,2600,'70');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,3142,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,3314,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,3340,'90');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,3515,'90');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,3637,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,4281,'90');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,4285,'90');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,4361,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,4650,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (20,4653,'100');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,11,'LAUNCH');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,41,'CARRY');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,56,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,75,'CARRY');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,102,'CARRY');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,193,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,219,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,222,'CARRY');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,555,'CARRY');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,613,'CARRY');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,1228,'CARRY');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,1279,'CARRY');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,1302,'CARRY');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,1370,'CATCH');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,1403,'CARRY');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,1676,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,1811,'CATCH');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,1923,'LAUNCH');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,2070,'CARRY');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,2458,'LAUNCH');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,2554,'CARRY');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,2559,'CARRY');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,2577,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,2600,'CARRY');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,3142,'CARRY');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,3314,'CARRY');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,3340,'CARRY');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,3515,'CARRY');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,3637,'CATCH');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,4281,'CARRY');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,4285,'CARRY');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,4361,'CARRY');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,4650,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (21,4653,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,11,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,41,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,56,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,75,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,102,'Two conveyors that create a "cage" around the ball. ');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,193,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,219,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,222,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,555,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,613,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,1228,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,1279,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,1302,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,1370,'Hold in net ');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,1403,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,1676,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,1811,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,1923,'Roller piece stays down');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,2070,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,2458,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,2554,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,2559,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,2577,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,2600,'Arm and a catapult');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,3142,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,3314,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,3340,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,3515,'Pick up us wing wheels');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,3637,'Clap of the roller and launcher');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,4281,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,4285,'Forklift sets it into a launcher');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,4361,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,4650,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (22,4653,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,11,'Rollers');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,41,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,56,'Yes');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,75,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,102,'From human player
Or attempt a catch');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,193,'Rollers');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,219,'Forklift');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,222,'Rollers suck ball up');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,555,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,613,'Roller');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,1228,'2 forks that pull the ball up into a basket thing');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,1279,'Rollers');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,1302,'Roller ');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,1370,'A wheel sucks the ball into a net');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,1403,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,1676,'Roller fold down');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,1811,'Rollers');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,1923,'Roller');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,2070,'It doesn''t ');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,2458,'Rollers and arms');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,2554,'Arms scoop like forklift');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,2559,'A forklift system ');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,2577,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,2600,'Pick up or human sets');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,3142,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,3314,'Two rollers');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,3340,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,3515,'Sets in');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,3637,'By a roller on the front of the robot');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,4281,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,4285,'Human player sets it');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,4361,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,4650,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (23,4653,'Lever picks up ball');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,11,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,41,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,56,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,75,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,102,'Get ball form human player , shoot over truss, play defense ');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,193,'Throw over truss');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,219,'None');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,222,'None');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,555,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,613,'None');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,1228,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,1279,'Mostly offensive but can do defense');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,1302,'None');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,1370,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,1403,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,1676,'Get the ball');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,1811,'Offensive');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,1923,'Shooting');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,2070,'Defense ');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,2458,'Mostly offense');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,2554,'Work with alliance defense');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,2559,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,2577,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,2600,'Offensive');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,3142,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,3314,'Offense');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,3340,'Defensive or low goal');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,3515,'Defensive');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,3637,'Revive and shoot');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,4281,'Passing/goals/defense ');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,4285,'Offensive');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,4361,'No strategy, flexible ');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,4650,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (24,4653,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,11,'Powder coating custom parts');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,41,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,56,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,75,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,102,'Two conveyor belts that squeeze the ball to shoot it. ');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,193,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,219,'Electromagnet');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,222,'Fast and accurate');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,555,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,613,'None');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,1228,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,1279,'Catapult');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,1302,'Custom parts');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,1370,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,1403,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,1676,'The wings are special catching is 66%');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,1811,'Very agile');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,1923,'Pass three different ways');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,2070,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,2458,'Good at picking ball up');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,2554,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,2559,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,2577,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,2600,'Fast and catapolt');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,3142,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,3314,'Powerful firing ');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,3340,'It picks up and deflects and can score in the low goal');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,3515,'Wheeled pick up ball and pass');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,3637,'Vex Challenge');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,4281,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,4285,'Forklift and launcher');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,4361,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,4650,'');
INSERT INTO `answers`(`question_id`,`team_number`,`answer`) VALUES (26,4653,'');
