Select team_number, num_matches, avg_pts, avg_auto_goal_pts, avg_auto_mobility_pts, avg_extra_goal_pts, avg_truss_pts, avg_catch_pts, avg_goal_pts, avg_assist_pts from team102_2014.team_avg_pts_norank_v
USE team102_2014;

latin1_swedish_ci;


INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (11,12,2.5,18.4,0.0,2.1,0.0,3.3,0.8,7.2,5,15.9);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (41,12,-10.2,4.2,0.0,4.2,0.0,0.0,0.0,0.0,0,14.4);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (56,11,12.9,34.3,9.5,4.5,1.3,5.5,0.9,5.3,7.3,21.3);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (75,12,18.7,29.2,6.5,4.2,0.3,2.5,0.8,4.2,10.8,10.6);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (102,12,2.7,13.1,5.0,5.0,0.1,0.0,0.8,0.1,2.1,10.4);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (193,11,8.7,21.5,1.4,4.5,0.2,2.7,0.0,3.5,9.1,12.7);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (219,12,-4.7,8,3.0,3.3,0.3,0.0,0.0,0.1,1.2,12.7);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (222,11,16.9,31.4,10.9,3.2,3.8,0.9,0.0,5.9,6.7,14.5);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (223,10,-4.9,13.7,3.0,4.0,2.1,1.0,0.0,2.1,1.5,18.6);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (224,11,0.2,12.5,2.5,3.2,0.1,0.9,1.8,0.9,3.2,12.3);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (265,11,-8.3,4.9,0.0,4.1,0.1,0.0,0.0,0.3,0.5,13.2);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (555,12,-11.2,7.1,1.3,1.3,0.0,0.0,0.0,0.0,4.6,18.3);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (613,11,-13.7,4.6,0.0,3.6,0.0,0.0,0.0,0.1,0.9,18.4);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (1228,11,2.8,23.3,8.2,5.0,1.2,4.5,0.0,2.1,2.3,20.5);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (1279,12,1,17.8,5.0,1.7,0.8,3.3,0.0,2.1,4.9,16.8);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (1302,12,-3.3,11,0.0,3.8,1.8,0.0,0.0,2.6,2.9,14.3);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (1370,11,-14.3,2.7,0.0,2.7,0.0,0.0,0.0,0.0,0,17);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (1403,12,33.7,45.8,6.3,4.2,6.7,2.5,1.7,20.0,4.6,12.1);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (1676,12,11.7,23.9,3.0,5.0,2.1,1.7,0.0,3.4,8.8,12.2);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (1811,11,-3.9,13.3,3.3,4.5,1.3,0.0,0.0,0.5,3.6,17.2);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (1923,11,19.2,34.1,10.9,3.2,4.5,0.9,0.9,9.1,4.5,14.9);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (2070,12,-11.7,3.3,0.0,2.9,0.0,0.0,0.0,0.0,0.4,15);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (2458,10,-13.5,4.5,0.6,3.0,0.2,0.0,0.0,0.2,0.5,18);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (2554,12,-19.2,1.8,0.0,0.0,0.0,0.0,0.0,0.2,1.7,21.1);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (2559,11,15.7,34.2,12.3,3.6,0.9,1.8,0.9,8.3,6.4,18.5);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (2577,11,3.7,19.1,10.1,4.5,0.4,0.0,0.0,1.4,2.7,15.4);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (2600,11,-3,7.4,0.5,4.1,0.0,0.9,0.0,0.0,1.8,10.4);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (3142,11,-1.8,9,0.0,5.0,0.1,0.0,0.0,0.7,3.2,10.8);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (3314,11,11.5,23,4.6,4.5,1.1,7.3,0.0,0.9,4.5,11.5);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (3340,11,-3.2,12.8,0.0,4.1,1.0,0.0,0.0,0.0,7.7,16);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (3515,12,-8.3,7.9,1.3,4.2,0.0,0.0,0.0,0.8,1.7,16.2);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (3637,12,-0.6,14,1.8,3.3,0.4,4.2,0.0,0.2,4.2,14.6);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (4035,11,4,13.9,1.4,3.6,3.7,0.9,0.0,1.1,3.2,9.9);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (4281,11,4.6,21.6,4.1,4.5,2.7,4.5,0.9,1.2,3.6,17);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (4285,11,-3.4,15.4,6.8,3.2,0.1,0.9,0.0,1.8,2.6,18.8);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (4361,12,-2.9,11.3,2.0,2.5,0.0,2.5,0.0,0.2,4.2,14.3);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (4650,12,-15.1,5.4,2.5,1.3,0.0,1.7,0.0,0.0,0,20.5);
INSERT INTO `team_avg_pts_norank_v`(`team_number`,`num_matches`,`avg_net_pts`,`avg_pts`,`avg_auto_goal_pts`,`avg_auto_mobility_pts`,`avg_extra_goal_pts`,`avg_truss_pts`,`avg_catch_pts`,`avg_goal_pts`,`avg_assist_pts`,`avg_pts_against`) VALUES (4653,11,-12.1,3.6,0.0,1.8,0.9,0.0,0.0,0.0,0.9,15.8);
